version: '3.7'

services:
  api-mygym-pg:
    image: bitnami/postgresql:latest
    container_name: api-mygym-pg-2
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apimygym
    ports:
      - '5433:5432'
