version: '3.7'

services:
  api-mygym-nest-pg:
    image: bitnami/postgresql:latest
    container_name: api-mygym-nest-pg
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apimygym
    ports:
      - '5432:5432'
